// Generates dist/sw.js after `vite build`: scans the build output and emits a
// cache-first service worker that precaches the entire app shell (JS, CSS,
// fonts, pixel-art assets, icons, manifest) so the app runs fully offline.

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const dist = path.resolve('dist');
if (!fs.existsSync(dist)) {
  console.error('dist/ not found — run vite build first');
  process.exit(1);
}

const files = [];
(function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(path.relative(dist, full).split(path.sep).join('/'));
  }
})(dist);

const precache = files.filter((f) => f !== 'sw.js');
// Version the cache by content hash so updates activate cleanly.
const hash = crypto.createHash('sha256');
for (const f of precache.sort()) {
  hash.update(f);
  hash.update(fs.readFileSync(path.join(dist, f)));
}
const version = hash.digest('hex').slice(0, 12);

const sw = `// generated by scripts/gen-sw.mjs — do not edit

// Cache names are namespaced by this registration's scope so that two
// installs sharing an origin (the Cache API, like IndexedDB, is scoped per
// origin and not per path) never touch each other's entries. Taking the
// namespace from the scope rather than from config keeps this generator free
// of any build-time coupling to src/config.
const PREFIX = 'routine-coins:' + self.registration.scope + ':';
const CACHE = PREFIX + '${version}';
// One-time cleanup of the pre-namespace cache name. Safe to delete once every
// install has activated a build that includes this line.
const LEGACY_PREFIX = 'haley-routine-';
const PRECACHE = ${JSON.stringify(['./', ...precache], null, 0)};

// Store responses with headers normalized (drop Vary) so cache hits never
// depend on request mode — servers often send "Vary: Origin", which would
// make crossorigin font/module requests miss the cache offline.
async function putNormalized(cache, url, res) {
  const headers = new Headers();
  for (const [k, v] of res.headers.entries()) {
    if (k.toLowerCase() !== 'vary') headers.set(k, v);
  }
  const body = await res.blob();
  await cache.put(url, new Response(body, { status: res.status, statusText: res.statusText, headers }));
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then(async (cache) => {
      await Promise.all(
        PRECACHE.map(async (url) => {
          const res = await fetch(url, { cache: 'no-cache' });
          if (!res.ok) throw new Error('precache failed: ' + url);
          await putNormalized(cache, url, res);
        })
      );
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      // Only ever delete OUR OWN stale caches. Deleting every key that isn't
      // CACHE would wipe the offline cache of any other app on this origin —
      // on a kiosk phone with unreliable wifi that is a real outage.
      Promise.all(
        keys
          .filter((k) => (k.startsWith(PREFIX) || k.startsWith(LEGACY_PREFIX)) && k !== CACHE)
          .map((k) => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

const MATCH_OPTS = { ignoreSearch: true, ignoreVary: true };

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  // App shell: any navigation serves the cached index.
  if (req.mode === 'navigate') {
    event.respondWith(
      caches.match('./', MATCH_OPTS).then((hit) => hit || fetch(req))
    );
    return;
  }
  // Everything else: cache-first, falling back to network (and caching it).
  event.respondWith(
    caches.match(req, MATCH_OPTS).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res && res.ok && new URL(req.url).origin === self.location.origin) {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => putNormalized(cache, req.url, copy));
        }
        return res;
      });
    })
  );
});
`;

fs.writeFileSync(path.join(dist, 'sw.js'), sw);
console.log(`sw.js written — ${precache.length} precached files, cache version ${version}`);
