// Generates dist/sw.js after `vite build`: scans the build output and emits a
// cache-first service worker that precaches the entire app shell (JS, CSS,
// fonts, pixel-art assets, icons, manifest) so the app runs fully offline.

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const dist = path.resolve('dist');
if (!fs.existsSync(dist)) {
  console.error('dist/ not found — run vite build first');
  process.exit(1);
}

const files = [];
(function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else files.push(path.relative(dist, full).split(path.sep).join('/'));
  }
})(dist);

const precache = files.filter((f) => f !== 'sw.js');
// Version the cache by content hash so updates activate cleanly.
const hash = crypto.createHash('sha256');
for (const f of precache.sort()) {
  hash.update(f);
  hash.update(fs.readFileSync(path.join(dist, f)));
}
const version = hash.digest('hex').slice(0, 12);

const sw = `// generated by scripts/gen-sw.mjs — do not edit
const CACHE = 'haley-routine-${version}';
const PRECACHE = ${JSON.stringify(['./', ...precache], null, 0)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  // App shell: any navigation serves the cached index.
  if (req.mode === 'navigate') {
    event.respondWith(
      caches.match('./').then((hit) => hit || fetch(req))
    );
    return;
  }
  // Everything else: cache-first, falling back to network (and caching it).
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res && res.ok && new URL(req.url).origin === self.location.origin) {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put(req, copy));
        }
        return res;
      });
    })
  );
});
`;

fs.writeFileSync(path.join(dist, 'sw.js'), sw);
console.log(`sw.js written — ${precache.length} precached files, cache haley-routine-${version}`);
